prubit_functionality/config/routes.rb
Rails.application.routes.draw do
  get "todos/index"
  
  match "todos/add" => "todos#add", :via => :post
  
  get "/todos/delete"

end

prubit_functionality/app/models/todo.rb
class Todo < ActiveRecord::Base

 attr_accessible :todo_item
 #The line lets the controller method mass assign value to the todo_item while creating a new entry in the database using Todo.create.
 #this is where attribute whitelisting would usually be done before rails 4.1, but now, it must be done in the controller. (WHY?)
 validates :todo_item, presence: true
 #validates is a rails model validation helper.
end

prubit_functionality/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

prubit_functionality/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index  #this is the index action of the todos controller
  	#by default this action fetches the index.html.erb file from views.
  	@todo_items = Todo.all #this fetches all todos from the Todo model and creates an instance variable @todo_items which is an array
  end

  def delete
  	#put delete logic here
  	t = Todo.last  #assign the last item on the todo list a variable t
  	t.delete     #delete that row.
  end

  def add
   todo = Todo.create(:todo_item => params[:todo_text])
   if !todo.valid?
        flash[:error] = todo.errors.full_messages.join("<br>").html_safe
   end
   redirect_to :action => 'index'
end

end

prubit_functionality/app/helpers/application_helper.rb
module ApplicationHelper
end

prubit_functionality/app/helpers/todos_helper.rb
module TodosHelper
end

prubit_functionality/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrubitFunctionality</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    
    <div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="#">Just Did it</a>
    </div>
    </div>

<%= yield %>

</body>
</html>

prubit_functionality/app/views/todos/delete.html.erb
<p>Todo successfully deleted</p>

<a href="/todos/index">Back</a>

prubit_functionality/app/views/todos/index.html.erb
<title>Shared To Do App</title>

<div class="container">
    <div class="row">
        <div class="span4">

      <h1>Your Prubit Page</h1>
<p>Find me in app/views/todos/index.html.erb</p>
<p> The controller has passed me an instance variable! <% @todo_item1 %></p>
<p>All your tasks here</p>
<%= form_tag("/todos/add", :method=>"post") do %>
  <%= text_field_tag(:todo_text) %>
  <%= submit_tag("Add todo", :class=>"btn") %>
<% end %>
<!--this is the same as writing: 
        <form accept-charset="UTF-8" action="/todos/add" method="post">
        <input id="todo_text" name="todo_text" type="text">
        <input name="commit" type="submit" class="btn" value="Add todo">
        </form>  -->
            
<% if !flash[:error].nil? %>
 <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert" >×</button>
    <strong><%= flash[:error] %></strong>
    </div>
<% end %>
            
    <div class="well">
    <% @todo_items.each do |taskName| %>
        <li><button class="TodosList"><%= taskName.todo_item %></button></li>
    <!-- This database needs more entries -->
    <% end %>

            </div> 
            </div>
        
        <div class="span8">
            <p>HERE IS WHERE GRAPHS AND SHIT WILL GO</p>
        </div>
        </div>
<a href="/todos/delete">Delete last todo</a>
   <!--could also write this as:  link_to "Delete last todo", delete_path %> -->

</div>